# ---
pool_1_name: "pool_1"
pool_2_name: "pool_2"
pool_port: "80"
pool_port_ssl: "443"
lb_method: "ratio_member"
slow_ramp_time: "120"
monitors: [ "/Common/http" ]
pool_1_members:
    - host: "10.3.0.201"
      port: "80"
    - host: "10.3.0.202"
      port: "80"
    - host: "10.3.0.203"
      port: "80"
pool_2_members:
    - host: "10.3.0.201"
      port: "80"
    - host: "10.3.0.202"
      port: "80"
    - host: "10.3.0.203"
      port: "80"
