---

# Note iApp Templates were installed in bigip_base role

- include: advanced.yaml
  when: iApp_advanced == "True"
  delegate_to: localhost

# Generate the iApp we will deploy from a template 
- name: Modify iApp to use VipAddress
  template: src="{{ jinja_template_name }}" dest="{{ install_path }}/cache/{{ env_tag }}/iApp-{{ iApp_service_name }}.json"
  delegate_to: localhost

- name: Deploy iApp Service
  delegate_to: localhost
  bigip_iapp_service:
      name: "{{ iApp_service_name }}"
      template: "{{ iApp_template_name }}"
      parameters: "{{ lookup('file', install_path + '/cache/' + env_tag + '/iApp-' + iApp_service_name + '.json') }}"
  register: result

