---
# iAPP VARS
# SERVICE VARS
service: "www.demo.f5example.com"
service_name: "www_demo_f5example_com"


vip_address: 10.1.1.1
vs_name: "{{ service_name }}_vs"
vs_description: "{{ service_name }} virtual service"
vs_port1: 443
vs_profiles1:
    - "http"
    - "{{ service_name }}_clientssl"

## SSL CERT 
client_ssl_cert_name: "{{ service_name }}"

# Static Pool Vars
pool_name: "{{ service_name }}_pool"
pool_port: "80"
pool_port_ssl: "443"
lb_method: "ratio_member"
slow_ramp_time: "120"
monitors: [ "/Common/http" ]
pool_members: 
    - host: "10.3.0.201"
      port: "80"
    - host: "10.3.0.202"
      port: "80"
    - host: "10.3.0.203"
      port: "80"

# iApp 2 pool example
pool_1_name: "pool_1"
pool_2_name: "pool_2"
pool_1_members:
    - host: "10.3.0.201"
      port: "80"
    - host: "10.3.0.202"
      port: "80"
    - host: "10.3.0.203"
      port: "80"
pool_2_members:
    - host: "10.3.0.201"
      port: "80"
    - host: "10.3.0.202"
      port: "80"
    - host: "10.3.0.203"
      port: "80"


# DNS Pool Vars
pool_dns: "www.f5.com"


# If Advanced
iApp_advanced: "False"
deployment_type: "lb_and_waf"
deploy_analytics: "true"

ltm_policy_name: "ltm_policy_w_asm_policy"
logging_profile_name: "asm_log_to_splunk"
analytics_profile_name: "my_analytics_profile"

# iApp Specific variables
iApp_service_name: "{{ service_name }}"
# TEMPLATE NAME:
iApp_template_name: "f5.http"
# Use for bigip_iApp_advanced
# iApp_template_name: "f5.http.v1.2.0"
# iApp_template_name: "appsvcs_integration_v2.1_001"
# TEMPLATE TYPE
iApp_template_type: "https_vip_create_new_pool"
# iApp_template_type: "https_vip_w_waf"
# iApp_template_type: "https_vip_w_waf_fqdn_pool"
# iApp_template_type: "wildcard_https_vip"
# iApp_template_type: "wildcard_https_vip_w_waf_fqdn_pool"

jinja_template_name: "{{ iApp_template_type + '_' + iApp_template_name + '.j2' }}"
